### PR TITLE
Added purple stamp shadow

### PR DESCRIPTION
**Pull request by UmungoBungo**
This one includes a bit more CSS than what your others have, so feel free to not approve the PR if it isn't the kind of thing you are looking for!

I think the text and border having the same purple as the shadow, and being on an angle, helps to give it a stamp effect.

### CODE REVIEW

**Comment by manuarora700** [comment]
Looks great! Merging it.

**Comment by UmungoBungo** [comment]
hey @manuarora700, I was expecting 

`customCSS: "text-purple-700 rotate-1 border-2 border-purple-700 rounded-md"`

to result in this:

image

It seems that the customCSS classes are being added, but their definitions aren't in the CSS when I inspect the object. Is it a build issue perhaps with JIT on Vercel, and the classes are being purged due to the way they are being included programmatically?

**Comment by manuarora700** [comment]
Oh my bad, forgot to update the safelist.txt file

**Comment by manuarora700** [comment]
Pushed the updated safelist classes. You should be able to see your changes in around minutes from now! 🚀

**Pull request merged**
